### ISSUE TITLE
Search: list values in alphabetic order

### ISSUE THREAD

**Issue by leolami** [g3w-suite/g3w-admin#173] opened 2020-12-11 15:25 UTC
The values ​​in the search drop-down menus should be sorted alphabetically

Try it the **Comuni costieri** search
https://v31.g3wsuite.it/en/map/arpa-liguria/qdjango/29/

V31 e DEV

Thanks

**Comment by wlorenzetti** [comment] 2021-02-19 11:04
Duplicate of #206

**Closed as completed by wlorenzetti** 2021-02-19 11:04 UTC
Labels: bug
