### ISSUE TITLE
Huey Consumer is not working after updating REDIS to v4.5.4

### ISSUE THREAD

**Issue by dotsLand** [g3w-suite/g3w-admin#527] opened 2023-04-07 13:15 UTC
### Checklist

- [X] I've searched through the existing [issues](https://github.com/g3w-suite/g3w-admin/issues) and this bug has never been reported before

### Subject of the issue

After updating a redis from `redis==3.5.3` to **`redis==4.5.4`**
i have this BUG
 
![image](https://user-images.githubusercontent.com/107835719/230613381-a84fc889-3098-4f4d-8265-7ca8d54eda6a.png)

After uninstall `redis==4.5.4` and install **`redis==3.5.3`** it work well

![image](https://user-images.githubusercontent.com/107835719/230614556-37030255-6874-4e54-b573-8b5c99d0aadd.png)

this is my redis Configuration

![image](https://user-images.githubusercontent.com/107835719/230614680-41fdf2df-e097-4e39-a049-fb77af849f13.png)

Also i tried to start direct from container G3W-suite **/usr/bin/xvfb-run -a python3 g3w-admin/manage.py run_huey** and same error

### Steps to reproduce

1. Update redis to `redis==4.5.3`
2. try to start docker consumer 
3. will see error on LOGS

After uninstall and again back to  redis==3.5.3 it is working 

### Environment

- g3w-admin: __3.5.dev__
- g3w-client: __3.8.0-alpha.2 dev__
- operating system: Docker Desktop 4.18.0 (104112)

**Comment by wlorenzetti** [comment] 2023-04-07 14:28
Hi @dotsLand, I try with `redis==4.5.4` and for task **`editing.tasks.editing_unlock`** it seams works fine.

In your trace error log I can see this custom task **`notify.tasks.task_notify`**, Is it a module of django-notify up?

**Comment by wlorenzetti** [comment] 2023-04-07 14:39
What's you Redis version?

**Comment by dotsLand** [comment] 2023-04-10 12:07
> Hi @dotsLand, I try with redis==4.5.4 and for task _editing.tasks.editing_unlock_ it seams works fine. In your trace error log I can see this custom task _notify.tasks.task_notify_, Is it a module of django-notify up?


I have tried with **REDIS v4.5.4**, it is the error that appears,

I currently have **REDIS v3.5.3** running

No, I'm not using django-notify, but I'm using `channels==2.2.0` `channels-redis==2.4.0` for web socket notification

**Comment by wlorenzetti** [comment] 2023-04-11 06:27
I never used channels, but sure.. I can understand the problem.

I think upgrading channels for example at version v4.0.0 it would work whit REDIS v.4.5.4.

The main problem is current Django version (v2.2), I hope to upgrade it to **Django v3.2** on next G3W-SUITE release (v3.6 or v3.7).

**Comment by wlorenzetti** [comment] 2023-04-11 06:29
If I understand correctly you are using G3W-SUITE with your custom module, if you can tell me what this module does, we are interested in knowing how G3W-SUITE is used :)

**Comment by dotsLand** [comment] 2023-04-12 06:56
> If I understand correctly you are using G3W-SUITE with your custom module, if you can tell me what this module does, we are interested in knowing how G3W-SUITE is used :)

I am looking the possibility of using this framework, and the possibility of adapting it to my case, disaster management and early warnings. I am still in the understanding of the framework and testing with some modules such as taking data and processing them through the HUEY task.

**Comment by Raruto** [comment] 2023-05-08 06:37
Hi @dotsLand, when you have some time please try again with latest [v3.6.0-alpha.0](https://github.com/g3w-suite/g3w-admin/tree/v.3.6.x) and let us know.

@wlorenzetti feel free to close this issue, if you think this is not a bug directly related to the core code

👋 Raruto

**Closed as completed** 2023-05-20 18:10 UTC
Labels: bug
