### ISSUE TITLE
Is there a limit to the maximum number of layers that can be managed by a web map?

### ISSUE THREAD

**Issue by pietroblu** [g3w-suite/g3w-admin#471] opened 2023-03-07 19:48 UTC
### Checklist

- [X] I've searched through the existing [issues](https://github.com/g3w-suite/g3w-client/issues) and this bug has never been reported before

### Subject of the issue

Hi all,
I've created a web map with a total of 52 vector layers (spatialite, shp and kmz) plus Bing Map as WMS.
When adding more layers, the client issues the error that is depicted in the following screenshot

![Screenshot 2023-03-07 202945](https://user-images.githubusercontent.com/3209793/223533435-0bba6f4b-7ff9-49fd-a7e1-e4a94af3650a.png)

Deleting the added layers, the error disappears.
Is there a limit to the maximum number of layers that can be managed by a web map?

Thank you for any reply.

### Steps to reproduce

1. Add layers to the QGIS project.
2. Upload data layers to file manager.
3. Upload QGIS project to the project manager.
4. Display the web map in browser.

### Environment

- g3w-docker: G3W-SUITE Versione 3.5.dev-20230306110125
- browser: Brave browser
- operating system: Windows 11

**Comment by wlorenzetti** [comment] 2023-03-08 07:43
Hi @pietroblu I don't think the issue is related to numbers of layers, G3w-SUITE is used for projects with hundreds of layers and it work fine. I think it could be related to VM capabilities in terms of Memory and CPU.

**Comment by wlorenzetti** [comment] 2023-03-08 07:45
I'll move this issue to g3w-admin repo.

**Comment by Raruto** [comment] 2023-08-29 10:15
> - browser: **Brave browser*
>
> When adding more layers, the client issues the error that is depicted in the following screenshot
>
> ![Screenshot 2023-03-07 202945](https://user-images.githubusercontent.com/3209793/223533435-0bba6f4b-7ff9-49fd-a7e1-e4a94af3650a.png)
>
> Deleting the added layers, the error disappears.

@pietroblu You should check the [browser console](https://firefox-source-docs.mozilla.org/devtools-user/browser_console/index.html) to see if there is any HTTP error.

It can also happen to see that warning when some layers are located on external servers or when using some additional browser settings (eg. ad-blockers, [https-only](https://support.mozilla.org/en-US/kb/https-only-prefs) mode, ...). <-- ref: **Brave browser**


For now, I'm closing here, do not hesitate to contact us if you have more information.

👋 Raruto

**Closed as completed by Raruto** 2023-08-29 10:15 UTC
Labels: question
